---
software_categories:
  foundation:
    packages:
      apt:
        - flatpak
        - snapd
        - software-properties-common
    dotfiles: []

  terminal:
    packages:
      apt:
        - alacritty
        - bat
        - fd-find  # fd in Debian
        - fzf
        - zoxide
        - neofetch
        - tree
        - wget
        - jq
        - file
        - unzip
        - zip
        - gettext
        - zsh
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - fonts-jetbrains-mono  # JetBrainsMono Nerd Font
      cargo:
        - du-dust  # dust package
      pip:
        - navi
    dotfiles:
      - { src: "config/alacritty", dest: ".config/alacritty" }
      - { src: ".zshrc", dest: ".zshrc" }
      - { src: ".bashrc", dest: ".bashrc" }
      - { src: ".gitconfig", dest: ".gitconfig" }
      - { src: "config/starship.toml", dest: ".config/starship.toml" }

  development:
    packages:
      apt:
        - git
        - gcc
        - ninja-build  # ninja in Debian
        - python3
        - python3-pip
        - python3-jupyter
        - docker.io
        - docker-compose
        - rustc
        - cargo
        - build-essential
      pip:
        - uv
    dotfiles:
      - { src: ".gitconfig", dest: ".gitconfig" }
      - { src: "config/nvim", dest: ".config/nvim" }

  desktop:
    packages:
      apt:
        - sway
        - waybar
        - wofi
        - mako-notifier  # mako in Debian
        - libnotify-bin  # libnotify
        - playerctl
        - wl-clipboard
        - clipman
        - grim
        - slurp
        - dolphin
        - redshift
        - pavucontrol  # For audio control
      flatpak:
        - com.spotify.Client
        - com.brave.Browser
        - com.discordapp.Discord
        - com.microsoft.Teams
        - org.gnome.Loupe
      snap:
        - nextcloud-desktop
    dotfiles:
      - { src: "config/sway", dest: ".config/sway" }
      - { src: "config/waybar", dest: ".config/waybar" }
      - { src: "config/wofi", dest: ".config/wofi" }
      - { src: "config/mako", dest: ".config/mako" }

  gaming:
    packages:
      flatpak:
        - org.prismlauncher.PrismLauncher
        - com.valvesoftware.Steam
    dotfiles: []

  uncategorized:
    packages:
      apt:
        - direnv
        - copyq
      cargo: []
      flatpak: []
      snap: []
      pip: []
      npm: []
    dotfiles: []
